name: SyncGitee
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/funnyzak
          dst: gitee/funnyzak
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: ${{ secrets.SYNC_REPOS }}
          set_about: true
          force_update: false
          debug: false
